# InferencePool Resource
apiVersion: inference.networking.k8s.io/v1
kind: InferencePool
metadata:
  name: food-review-inference-pool
  namespace: default
spec:
  selector:
    matchLabels:
      app: food-review-inference-pool
  endpointPickerRef:
    name: food-review-endpoint-picker
    kind: Service
    port:
      number: 9002
  targetPorts:
  - number: 8000
