kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: llm-d-inference-scheduler-dev
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  # Inference Scheduler
  - containerPort: 30080
    hostPort: 8080
    protocol: TCP
  # vLLM TTS backend
  - containerPort: 30081
    hostPort: 8081
    protocol: TCP
  # vLLM STT backend
  - containerPort: 30082
    hostPort: 8082
    protocol: TCP
  # vLLM Image Generation backend
  - containerPort: 30083
    hostPort: 8083
    protocol: TCP
  # Standard LLM backend
  - containerPort: 30084
    hostPort: 8084
    protocol: TCP
