---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-tts-sim
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multimodal-inference-pool
      llm-d.ai/model-arch: autoregressive-tts
  template:
    metadata:
      labels:
        app: multimodal-inference-pool
        llm-d.ai/engine-type: vllm
        llm-d.ai/model-arch: autoregressive-tts
    spec:
      containers:
      - name: vllm-sim
        image: ${VLLM_IMAGE}
        imagePullPolicy: IfNotPresent
        args:
        - --model
        - OuteAI/OuteTTS-0.3-1B
        - --port
        - "8000"
        - --mode
        - echo
        - --log-http
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-stt-sim
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multimodal-inference-pool
      llm-d.ai/model-arch: encoder-decoder-stt
  template:
    metadata:
      labels:
        app: multimodal-inference-pool
        llm-d.ai/engine-type: vllm
        llm-d.ai/model-arch: encoder-decoder-stt
    spec:
      containers:
      - name: vllm-sim
        image: ${VLLM_IMAGE}
        imagePullPolicy: IfNotPresent
        args:
        - --model
        - openai/whisper-large-v3
        - --port
        - "8000"
        - --mode
        - echo
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
